CREATE DATABASE IF NOT EXISTS niyati_canteen CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE niyati_canteen;

CREATE TABLE roles (id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(32) NOT NULL UNIQUE, name VARCHAR(64) NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
-- Explicit CHARACTER SET/COLLATE here (rather than relying on the CREATE
-- DATABASE default above) so a fresh install gets the intended collation
-- regardless of what collation the hosting environment's database actually
-- ended up with — see database/migrations/012_standardize_user_collation.sql
-- for the corresponding fix on an already-existing database.
CREATE TABLE users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, role_id TINYINT UNSIGNED NOT NULL, email VARCHAR(150) NOT NULL UNIQUE, display_name VARCHAR(100) NOT NULL, mobile VARCHAR(15) NULL, password_hash VARCHAR(255) NOT NULL, active TINYINT(1) NOT NULL DEFAULT 1, last_login_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id)) ENGINE=InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE menu_categories (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, active TINYINT(1) NOT NULL DEFAULT 1, sort_order INT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE menu_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, category_id BIGINT UNSIGNED NOT NULL, name VARCHAR(150) NOT NULL, description TEXT NULL, price DECIMAL(12,2) NULL, image_path VARCHAR(255) NULL, active TINYINT(1) NOT NULL DEFAULT 1, sort_order INT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_menu_category(category_id), INDEX idx_menu_active(active), CONSTRAINT fk_menu_category FOREIGN KEY (category_id) REFERENCES menu_categories(id)) ENGINE=InnoDB;
CREATE TABLE menu_item_variants (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, menu_item_id BIGINT UNSIGNED NOT NULL, name VARCHAR(100) NOT NULL, price DECIMAL(12,2) NOT NULL, active TINYINT(1) NOT NULL DEFAULT 1, sort_order INT NOT NULL DEFAULT 0, CONSTRAINT fk_variant_item FOREIGN KEY (menu_item_id) REFERENCES menu_items(id), UNIQUE KEY uniq_variant_name(menu_item_id,name)) ENGINE=InnoDB;
CREATE TABLE menu_item_price_history (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, menu_item_id BIGINT UNSIGNED NOT NULL, old_price DECIMAL(12,2) NULL, new_price DECIMAL(12,2) NULL, changed_by BIGINT UNSIGNED NOT NULL, changed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_price_item FOREIGN KEY(menu_item_id) REFERENCES menu_items(id), CONSTRAINT fk_price_user FOREIGN KEY(changed_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE canteen_tables (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, table_name VARCHAR(64) NOT NULL UNIQUE, kind ENUM('TABLE','PARCEL') NOT NULL DEFAULT 'TABLE', status ENUM('AVAILABLE','OCCUPIED','BILLING','RESERVED') NOT NULL DEFAULT 'AVAILABLE', active TINYINT(1) NOT NULL DEFAULT 1, sort_order INT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE orders (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_number VARCHAR(40) NULL UNIQUE, bill_number VARCHAR(40) NULL UNIQUE, table_id BIGINT UNSIGNED NULL, order_type ENUM('TABLE','TAKEAWAY') NOT NULL DEFAULT 'TABLE', status ENUM('DRAFT','OPEN','SERVED','PAID','CANCELLED') NOT NULL DEFAULT 'DRAFT', subtotal DECIMAL(12,2) NOT NULL DEFAULT 0, discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0, complementary_amount DECIMAL(12,2) NOT NULL DEFAULT 0, grand_total DECIMAL(12,2) NOT NULL DEFAULT 0, payment_status ENUM('UNPAID','PAID','PARTIAL') NOT NULL DEFAULT 'UNPAID', created_by BIGINT UNSIGNED NOT NULL, updated_by BIGINT UNSIGNED NOT NULL, completed_at DATETIME NULL, cancelled_at DATETIME NULL, cancelled_by BIGINT UNSIGNED NULL, cancellation_reason VARCHAR(500) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_orders_table(table_id), INDEX idx_orders_status(status), INDEX idx_orders_created(created_at), INDEX idx_orders_order_number(order_number), CONSTRAINT fk_order_table FOREIGN KEY(table_id) REFERENCES canteen_tables(id), CONSTRAINT fk_order_creator FOREIGN KEY(created_by) REFERENCES users(id), CONSTRAINT fk_order_updater FOREIGN KEY(updated_by) REFERENCES users(id), CONSTRAINT fk_order_canceller FOREIGN KEY(cancelled_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE order_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id BIGINT UNSIGNED NOT NULL, menu_item_id BIGINT UNSIGNED NOT NULL, menu_item_variant_id BIGINT UNSIGNED NULL, item_name_snapshot VARCHAR(180) NOT NULL, variant_name_snapshot VARCHAR(100) NULL, quantity INT UNSIGNED NOT NULL, unit_price DECIMAL(12,2) NOT NULL, gross_amount DECIMAL(12,2) NOT NULL, discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0, complementary_amount DECIMAL(12,2) NOT NULL DEFAULT 0, net_amount DECIMAL(12,2) NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_order_items_order(order_id), CONSTRAINT fk_order_item_order FOREIGN KEY(order_id) REFERENCES orders(id), CONSTRAINT fk_order_item_menu FOREIGN KEY(menu_item_id) REFERENCES menu_items(id), CONSTRAINT fk_order_item_variant FOREIGN KEY(menu_item_variant_id) REFERENCES menu_item_variants(id)) ENGINE=InnoDB;
CREATE TABLE discounts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id BIGINT UNSIGNED NOT NULL, discount_type ENUM('PERCENT','FIXED') NOT NULL, discount_value DECIMAL(12,2) NOT NULL, discount_amount DECIMAL(12,2) NOT NULL, reason VARCHAR(500) NULL, applied_by BIGINT UNSIGNED NOT NULL, applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, active TINYINT(1) NOT NULL DEFAULT 1, CONSTRAINT fk_discount_order FOREIGN KEY(order_id) REFERENCES orders(id), CONSTRAINT fk_discount_user FOREIGN KEY(applied_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE complementary_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_item_id BIGINT UNSIGNED NOT NULL, original_amount DECIMAL(12,2) NOT NULL, complementary_amount DECIMAL(12,2) NOT NULL, reason VARCHAR(500) NULL, applied_by BIGINT UNSIGNED NOT NULL, applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, active TINYINT(1) NOT NULL DEFAULT 1, CONSTRAINT fk_comp_item FOREIGN KEY(order_item_id) REFERENCES order_items(id), CONSTRAINT fk_comp_user FOREIGN KEY(applied_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE payments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id BIGINT UNSIGNED NOT NULL, method ENUM('CASH','UPI','OTHER') NOT NULL, amount DECIMAL(12,2) NOT NULL, received_by BIGINT UNSIGNED NOT NULL, paid_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_payment_order FOREIGN KEY(order_id) REFERENCES orders(id), CONSTRAINT fk_payment_user FOREIGN KEY(received_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE order_audits (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, action VARCHAR(64) NOT NULL, old_values JSON NULL, new_values JSON NULL, reason VARCHAR(500) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_order_audits_order(order_id), CONSTRAINT fk_order_audit_order FOREIGN KEY(order_id) REFERENCES orders(id), CONSTRAINT fk_order_audit_user FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE bill_audits (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, action VARCHAR(64) NOT NULL, old_values JSON NULL, new_values JSON NULL, reason VARCHAR(500) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_bill_audit_order FOREIGN KEY(order_id) REFERENCES orders(id), CONSTRAINT fk_bill_audit_user FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE settings (setting_key VARCHAR(100) PRIMARY KEY, setting_value TEXT NOT NULL, updated_by BIGINT UNSIGNED NULL, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT fk_settings_user FOREIGN KEY(updated_by) REFERENCES users(id)) ENGINE=InnoDB;
-- Single-row, transaction-safe counter for the human-readable bill number
-- (see OrderService::nextBillSequence). Deliberately independent of
-- orders.id and of any date, so numbering is continuous, never resets, and
-- is never wasted on a rolled-back payment.
CREATE TABLE bill_sequence (id TINYINT UNSIGNED NOT NULL PRIMARY KEY, next_number INT UNSIGNED NOT NULL) ENGINE=InnoDB;
CREATE TABLE order_sequence (id TINYINT UNSIGNED NOT NULL PRIMARY KEY, next_number INT UNSIGNED NOT NULL) ENGINE=InnoDB;
CREATE TABLE permissions (code VARCHAR(40) PRIMARY KEY, name VARCHAR(100) NOT NULL, sort_order INT NOT NULL DEFAULT 0) ENGINE=InnoDB;
CREATE TABLE user_permissions (user_id BIGINT UNSIGNED NOT NULL, permission_code VARCHAR(40) NOT NULL, granted_by BIGINT UNSIGNED NULL, granted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id,permission_code), CONSTRAINT fk_up_user FOREIGN KEY(user_id) REFERENCES users(id), CONSTRAINT fk_up_permission FOREIGN KEY(permission_code) REFERENCES permissions(code), CONSTRAINT fk_up_granter FOREIGN KEY(granted_by) REFERENCES users(id)) ENGINE=InnoDB;
-- Print bridge architecture (see database/migrations/013_print_bridge_architecture.sql for rationale).
CREATE TABLE counters (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, active TINYINT(1) NOT NULL DEFAULT 1, sort_order INT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE print_bridges (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, counter_id BIGINT UNSIGNED NOT NULL, bridge_code VARCHAR(20) NOT NULL UNIQUE, token_hash CHAR(64) NOT NULL UNIQUE, printers_json TEXT NULL, last_seen_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by BIGINT UNSIGNED NOT NULL, INDEX idx_bridge_counter(counter_id), CONSTRAINT fk_bridge_counter FOREIGN KEY(counter_id) REFERENCES counters(id), CONSTRAINT fk_bridge_creator FOREIGN KEY(created_by) REFERENCES users(id)) ENGINE=InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE TABLE print_jobs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, counter_id BIGINT UNSIGNED NOT NULL, order_id BIGINT UNSIGNED NULL, job_type VARCHAR(30) NOT NULL DEFAULT 'RECEIPT', paper_width ENUM('58','80') NOT NULL DEFAULT '80', payload MEDIUMTEXT NOT NULL, status ENUM('QUEUED','PROCESSING','PRINTED','FAILED','CANCELLED') NOT NULL DEFAULT 'QUEUED', attempts INT UNSIGNED NOT NULL DEFAULT 0, last_error VARCHAR(500) NULL, created_by BIGINT UNSIGNED NOT NULL, claimed_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, claimed_at DATETIME NULL, printed_at DATETIME NULL, INDEX idx_print_jobs_counter_status(counter_id,status), INDEX idx_print_jobs_order(order_id), CONSTRAINT fk_pj_counter FOREIGN KEY(counter_id) REFERENCES counters(id), CONSTRAINT fk_pj_order FOREIGN KEY(order_id) REFERENCES orders(id), CONSTRAINT fk_pj_creator FOREIGN KEY(created_by) REFERENCES users(id), CONSTRAINT fk_pj_bridge FOREIGN KEY(claimed_by) REFERENCES print_bridges(id)) ENGINE=InnoDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
INSERT INTO counters(name,sort_order) VALUES ('Counter 1',1);
